
server:
  port: 8888
spring:
  application:
    name: service-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/a-farsi/spring-config-repo
          search-paths: configs
          default-label: main
      enabled: true
    discovery:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

  instance:
    prefer-ip-address: true
